#!/usr/bin/env bash
# Build example/python/viz_example/viz.py into a single executable with PyInstaller.
#
# Prerequisites:
#   - SDK built: ./build.sh  (from repo root)
#   - PyInstaller: pip install pyinstaller
#
# Output:
#   example/python/viz_example/dist/magicbot_z1_viz

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDK_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SDK_BUILD="${MAGICBOT_Z1_SDK_BUILD:-$SDK_ROOT/build}"

PY="${MAGICBOT_VIZ_PYTHON:-python3}"
if ! "$PY" -m PyInstaller --version >/dev/null 2>&1; then
  echo "错误: 未找到 PyInstaller，请先安装: $PY -m pip install pyinstaller" >&2
  exit 1
fi

PYBIND_SO=""
for f in "$SDK_BUILD"/magicbot_z1_python.cpython-*.so; do
  if [[ -f "$f" ]]; then
    PYBIND_SO="$f"
    break
  fi
done
SDK_LIB="$SDK_BUILD/libmagicbot_z1_sdk.so"

if [[ -z "$PYBIND_SO" || ! -f "$SDK_LIB" ]]; then
  echo "错误: 未找到 SDK 构建产物，请在仓库根目录执行 ./build.sh" >&2
  echo "  期望: $SDK_BUILD/magicbot_z1_python.cpython-*.so" >&2
  echo "  期望: $SDK_LIB" >&2
  exit 1
fi

echo "SDK 绑定: $PYBIND_SO"
echo "SDK 库:   $SDK_LIB"

SPEC="$SCRIPT_DIR/magicbot_z1_viz.spec"
cat >"$SPEC" <<EOF
# -*- mode: python ; coding: utf-8 -*-
# Generated by build_viz.sh — do not edit by hand; re-run the script instead.

from PyInstaller.utils.hooks import collect_all

datas = []
binaries = [
    ('${PYBIND_SO}', '.'),
    ('${SDK_LIB}', '.'),
]
hiddenimports = ['magicbot_z1_python']
tmp_ret = collect_all('tkinter')
datas += tmp_ret[0]
binaries += tmp_ret[1]
hiddenimports += tmp_ret[2]

a = Analysis(
    ['${SCRIPT_DIR}/viz.py'],
    pathex=['${SCRIPT_DIR}'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['${SCRIPT_DIR}/pyi_rth_magicbot_z1.py'],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='magicbot_z1_viz',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
EOF

cd "$SCRIPT_DIR"
"$PY" -m PyInstaller --noconfirm --clean "$SPEC"

echo ""
echo "构建完成: $SCRIPT_DIR/dist/magicbot_z1_viz"
ls -lh "$SCRIPT_DIR/dist/magicbot_z1_viz"
echo ""
echo "glibc 要求: 请在 glibc >= $(ldd --version 2>/dev/null | awk 'NR==1{print $NF}') 的系统上运行，"
echo "或在更旧系统（如 Ubuntu 20.04 机载环境）上使用 ./build_viz_docker.sh 重新打包。"

