# -*- mode: python ; coding: utf-8 -*-
# Generated by build_viz.sh — do not edit by hand; re-run the script instead.

from PyInstaller.utils.hooks import collect_all

datas = []
binaries = [
    ('/home/shanchao/robot/robot_magiclab/SDK/magicbot_z1_sdk/build/magicbot_z1_python.cpython-310-x86_64-linux-gnu.so', '.'),
    ('/home/shanchao/robot/robot_magiclab/SDK/magicbot_z1_sdk/build/libmagicbot_z1_sdk.so', '.'),
]
hiddenimports = ['magicbot_z1_python']
tmp_ret = collect_all('tkinter')
datas += tmp_ret[0]
binaries += tmp_ret[1]
hiddenimports += tmp_ret[2]

a = Analysis(
    ['/home/shanchao/robot/robot_magiclab/SDK/magicbot_z1_sdk/example/python/viz_example/viz.py'],
    pathex=['/home/shanchao/robot/robot_magiclab/SDK/magicbot_z1_sdk/example/python/viz_example'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['/home/shanchao/robot/robot_magiclab/SDK/magicbot_z1_sdk/example/python/viz_example/pyi_rth_magicbot_z1.py'],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='magicbot_z1_viz',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
